# landmarks coordinates should be provided in the ground_truth reference frame
landmarks:
  id: [0, 1, 2, 3 ,4 ,5, 6, 7, 8]
  x: [1.20, 1.68, 3.72, 3.75, 2.48, 4.80, 2.18, 2.94]
  y: [1.68, -0.05, 0.14, 1.37,1.25, 1.87, 1.00, 2.70]
  z: [0.16, 0.18, 0.22, 0.21, 0.22, 0.24, 0.24, 0.73]